import {
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  AudioLines,
  Award,
  BarChart3,
  BookmarkCheck,
  Brain,
  Briefcase,
  Calendar,
  Check,
  CheckCircle,
  CreditCard,
  FileCheck,
  FileText,
  Flag,
  Gauge,
  GraduationCap,
  Layers,
  LayoutDashboard,
  Map,
  MessageCircle,
  MessageSquare,
  Mic,
  PlayCircle,
  Plus,
  Radar,
  Rocket,
  Route,
  Search,
  Send,
  SlidersHorizontal,
  Sparkles,
  Target,
  TrendingUp,
  UserPlus,
  type LucideProps,
} from 'lucide-react'

const icons = {
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  'audio-lines': AudioLines,
  award: Award,
  'bar-chart-3': BarChart3,
  'bookmark-check': BookmarkCheck,
  brain: Brain,
  briefcase: Briefcase,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'credit-card': CreditCard,
  'file-check': FileCheck,
  'file-text': FileText,
  flag: Flag,
  gauge: Gauge,
  'graduation-cap': GraduationCap,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  map: Map,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  mic: Mic,
  'play-circle': PlayCircle,
  plus: Plus,
  radar: Radar,
  rocket: Rocket,
  route: Route,
  search: Search,
  send: Send,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  target: Target,
  'trending-up': TrendingUp,
  'user-plus': UserPlus,
}

export type IconName = keyof typeof icons

export default function SiteIcon({
  name,
  ...props
}: LucideProps & { name: IconName }) {
  const Icon = icons[name]
  return <Icon {...props} />
}
